apiVersion: v1
kind: Service
metadata:
  name: kandula-app-service
spec:
  selector:
    app: kandula-app
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 5000
      protocol: TCP
